FROM ruby:2.5

MAINTAINER dev@codeship.com

RUN apt-get update -y && apt-get install -y \
  build-essential

# Copy Everything Else Needed for CI
COPY . ./

# Shipyard Documentation
WORKDIR /styleguide/
RUN gem install bundler --pre --no-ri --no-rdoc && bundle install --jobs 20 --retry 5
EXPOSE 4000

WORKDIR /styleguide/_site/

CMD [ "bundle", "exec", "jekyll", "serve", "--force_polling", "-H", "0.0.0.0", "-P", "4000" ]
