source 'https://rubygems.org'

group :jekyll_plugins do
  gem 'sprockets', '~> 4.0.0.beta8'
  gem 'jekyll', '~> 4.1', '>= 4.1.1'
  gem "jekyll-assets", git: "https://github.com/envygeeks/jekyll-assets"
  gem 'shipyard-framework', path: '../'
  gem 'rake' # Needed for Codeship to install the sassc gem
  gem 'sass'
  gem 'sassc'
  gem 'uglifier'
  gem 'html-proofer'
end
