source 'https://rubygems.org'

group :jekyll_plugins do
  gem 'jekyll', '~> 3.8.3'
  gem 'jekyll-assets', '~> 3.0.11'
  gem 'shipyard-framework', path: '../'
  gem 'rake' # Needed for Codeship to install the sassc gem
  gem 'sassc', '~> 1.11.4'
  gem 'uglifier'
  gem 'html-proofer'
end
