#!/bin/bash

echo -e "************** Setup Commands **************"
set -e

echo -e "\n\n************** Git Clone GH-Pages Branch **************"
git clone git@github.com:codeship/shipyard.git --branch gh-pages --single-branch styleguide/_site

echo -e "\n\n************** Jekyll Build **************"
cd styleguide
JEKYLL_ENV=production bundle exec jekyll build --verbose

echo -e "\n\n************** Commit & Push to GitHub Pages **************"
cd _site
git config user.email "${GITHUB_DEPLOY_USER_EMAIL}"
git config user.name "${GITHUB_DEPLOY_USER_NAME}"
git status
git add --all
git status
git commit --allow-empty -m "Deploy to GitHub Pages: ${CI_COMMIT_ID} --skip-ci"
git push origin gh-pages
