#!/bin/bash
set -e # halt script on error

echo -e "\n\n************** Git Clone GH-Pages Branch **************"
git clone https://github.com/codeship/shipyard.git --branch gh-pages --single-branch styleguide/_site

echo -e "\n\n************** Jekyll Build **************"
cd styleguide
JEKYLL_ENV=production bundle exec jekyll build --verbose

echo -e "\n\n************** Commit & Push to GitHub Pages **************"
cd _site
git config user.email "${GITHUB_DEPLOY_USER_EMAIL}"
git config user.name "${GITHUB_DEPLOY_USER_NAME}"
git status
git add --all
git status

if [[ $CI_NAME = "codeship" ]]
then
  git commit --allow-empty -m "Deploy to GitHub Pages: ${CI_COMMIT_ID} --skip-ci"
  # push to GitHub using -q so the API token does not show
  git push -q "https://${GITHUB_DEPLOY_USER_API_KEY}@github.com/codeship/shipyard gh-pages
else
  git commit --allow-empty -m "Dry Run Deploy: --skip-ci"
  git push --dry-run origin gh-pages
fi
